const KEY='souk_professional_listings_v3';
const demo=[
{id:'demo1',kind:'بيع',category:'زيت الزيتون',title:'زيت زيتون بكر ممتاز – موسم 2026',price:'85 درهم / لتر',location:'مراكش',quantity:'500 لتر',unit:'معصرة مهنية',phone:'0612345678',whatsapp:'0612345678',onssa:'حاصل',condition:'جديد',description:'زيت زيتون بكر ممتاز من إنتاج وحدة مهنية، معبأ بعناية. الكمية المعروضة 500 لتر، ويمكن الاتفاق على الكمية حسب الحاجة.',image:'assets/oil-demo.svg',createdAt:'2026-09-28T10:00:00Z'},
{id:'demo2',kind:'بيع',category:'المعدات والتجهيزات',title:'فلتر صفائحي لتصفية زيت الزيتون',price:'18,500 درهم',location:'قلعة السراغنة',quantity:'1',unit:'وحدة مهنية',phone:'0623456789',whatsapp:'0623456789',condition:'مستعمل بحالة جيدة',description:'فلتر صفائحي مناسب لخطوط تصفية زيت الزيتون، جاهز للاستعمال، مع إمكانية المعاينة قبل الشراء.',image:'assets/filter-demo.svg',createdAt:'2026-09-27T10:00:00Z'},
{id:'demo3',kind:'بيع',category:'المعدات والتجهيزات',title:'خزان ستانلس ستيل 1000 لتر',price:'12,000 درهم',location:'العطاوية',quantity:'2',unit:'معصرة',phone:'0634567890',whatsapp:'0634567890',condition:'مستعمل',description:'خزانات ستانلس ستيل مخصصة لحفظ زيت الزيتون، سعة 1000 لتر للخزان الواحد.',image:'assets/tank-demo.svg',createdAt:'2026-09-26T10:00:00Z'},
{id:'demo4',kind:'شراء',category:'المعدات والتجهيزات',title:'مطلوب مضخة زيت غذائية',price:'الميزانية حسب الحالة',location:'بني ملال',quantity:'1',unit:'معصرة مهنية',phone:'0645678901',whatsapp:'0645678901',condition:'مستعمل أو جديد',description:'نبحث عن مضخة مناسبة لضخ زيت الزيتون، مع ذكر القدرة والحالة والسعر المقترح.',image:'assets/pump-demo.svg',createdAt:'2026-09-25T10:00:00Z'}];
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function listings(){try{const x=JSON.parse(localStorage.getItem(KEY));return Array.isArray(x)&&x.length?x:demo}catch{return demo}}
function saveListings(a){localStorage.setItem(KEY,JSON.stringify(a))}
function wa(n){let x=String(n||'').replace(/\D/g,'');if(x.startsWith('0'))x='212'+x.slice(1);if(!x.startsWith('212'))x='212'+x;return 'https://wa.me/'+x}
function phoneHref(n){return 'tel:'+String(n||'').replace(/\s/g,'')}
function card(x){return `<article class="card"><a href="listing.html?id=${encodeURIComponent(x.id)}"><div class="card-image"><img src="${esc(x.image||'assets/oil-demo.svg')}" alt="${esc(x.title)}"><span class="badge ${x.kind==='بيع'?'sale':'buy'}">${x.kind==='بيع'?'للبيع':'مطلوب للشراء'}</span></div><div class="card-body"><h3>${esc(x.title)}</h3><div class="price">${esc(x.price||'السعر عند التواصل')}</div><div class="meta"><span>📍 ${esc(x.location)}</span><span>${x.category==='زيت الزيتون'?'🫒':'⚙️'} ${esc(x.category)}</span></div><div class="card-footer"><small>${esc(x.quantity||'')} ${x.quantity?'— ':''}${esc(x.condition||'')}</small><span class="link">التفاصيل ←</span></div></div></a></article>`}
function getById(id){return listings().find(x=>x.id===id)}
function renderGrid(el,arr){el.innerHTML=arr.length?arr.map(card).join(''):`<div class="empty" style="grid-column:1/-1"><b>لا توجد نتائج حالياً</b>غيّر خيارات البحث أو انشر أول إعلان في المنصة.</div>`}
function filterData(){const c=document.getElementById('cat')?.value||'الكل',k=document.getElementById('kind')?.value||'الكل',q=(document.getElementById('q')?.value||'').trim().toLowerCase();return listings().filter(x=>(c==='الكل'||x.category===c)&&(k==='الكل'||x.kind===k)&&(!q||JSON.stringify(x).toLowerCase().includes(q))).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt))}
function initHome(){const grid=document.getElementById('homeGrid');if(grid)renderGrid(grid,listings().slice().sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,4));document.getElementById('searchGo')?.addEventListener('click',()=>{const q=document.getElementById('homeSearch').value.trim();location.href='search.html?q='+encodeURIComponent(q)});document.getElementById('homeSearch')?.addEventListener('keydown',e=>{if(e.key==='Enter')document.getElementById('searchGo').click()})}
function initSearch(){const p=new URLSearchParams(location.search);const q=p.get('q')||'';document.getElementById('q').value=q;const run=()=>renderGrid(document.getElementById('grid'),filterData());['cat','kind','q'].forEach(id=>document.getElementById(id)?.addEventListener('input',run));run()}
function initDetail(){const x=getById(new URLSearchParams(location.search).get('id'));const root=document.getElementById('detail');if(!x){root.innerHTML='<div class="empty">الإعلان غير موجود.</div>';return}root.innerHTML=`<div class="detail-layout"><div class="gallery"><div class="gallery-main"><img src="${esc(x.image||'assets/oil-demo.svg')}" alt="${esc(x.title)}"></div></div><div class="detail-box"><span class="eyebrow">${x.kind==='بيع'?'عرض للبيع':'طلب شراء'} · ${esc(x.category)}</span><h1>${esc(x.title)}</h1><div class="detail-price">${esc(x.price||'السعر عند التواصل')}</div><div class="meta"><span>📍 ${esc(x.location)}</span><span>🕒 منشور حديثاً</span></div><div class="specs"><div class="spec"><small>الكمية</small><b>${esc(x.quantity||'—')}</b></div><div class="spec"><small>الحالة</small><b>${esc(x.condition||'—')}</b></div><div class="spec"><small>الوحدة / الجهة</small><b>${esc(x.unit||'—')}</b></div>${x.category==='زيت الزيتون'?`<div class="spec"><small>الترخيص الصحي</small><b>${esc(x.onssa||'—')}</b></div>`:''}</div><h3>الوصف</h3><p class="detail-desc">${esc(x.description||'لا يوجد وصف إضافي.')}</p><div class="contact"><a class="btn primary" href="${phoneHref(x.phone)}">📞 الاتصال</a><a class="btn whatsapp" target="_blank" rel="noopener" href="${wa(x.whatsapp||x.phone)}">◉ واتساب</a></div><div class="notice" style="margin-top:14px">التواصل يتم مباشرة مع صاحب الإعلان. المنصة لا تتدخل في إتمام المعاملة بين الطرفين.</div></div></div>`}
function initPublish(){const form=document.getElementById('publishForm');document.getElementById('lawLink')?.addEventListener('click',()=>document.getElementById('lawModal').classList.add('open'));document.querySelectorAll('[data-close-law]').forEach(x=>x.addEventListener('click',()=>document.getElementById('lawModal').classList.remove('open')));document.getElementById('kind')?.addEventListener('change',()=>{});form?.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(form);const x=Object.fromEntries(fd.entries());if(!fd.get('agree'))return alert('يرجى الموافقة على القانون الداخلي أولاً.');if(x.category==='زيت الزيتون'&&x.onssa!=='حاصل')return alert('إعلانات زيت الزيتون مخصصة للوحدات الحاصلة على الترخيص الصحي.');x.id='ad_'+Date.now();x.createdAt=new Date().toISOString();x.image=x.category==='زيت الزيتون'?'assets/oil-demo.svg':x.category==='المعدات والتجهيزات'?'assets/filter-demo.svg':'assets/oil-demo.svg';const old=listings().filter(z=>!z.id.startsWith('demo'));saveListings([x,...old]);location.href='search.html';})}
window.Souk={listings,saveListings,initHome,initSearch,initDetail,initPublish};
