const KEY='souk_professional_listings_v3';
const DB_NAME='souk_market_media_v3';
const DB_VERSION=1;
const MEDIA_STORE='media';
const demo=[
{id:'demo1',kind:'بيع',category:'زيت الزيتون',title:'زيت زيتون بكر ممتاز – موسم 2026',price:'85 درهم / لتر',location:'مراكش',quantity:'500 لتر',unit:'معصرة مهنية',phone:'0612345678',whatsapp:'0612345678',onssa:'حاصل',condition:'جديد',description:'زيت زيتون بكر ممتاز من إنتاج وحدة مهنية، معبأ بعناية. الكمية المعروضة 500 لتر، ويمكن الاتفاق على الكمية حسب الحاجة.',media:[{type:'image',url:'assets/oil-demo.svg'}],createdAt:'2026-09-28T10:00:00Z'},
{id:'demo2',kind:'بيع',category:'المعدات والتجهيزات',title:'فلتر صفائحي لتصفية زيت الزيتون',price:'18,500 درهم',location:'قلعة السراغنة',quantity:'1',unit:'وحدة مهنية',phone:'0623456789',whatsapp:'0623456789',condition:'مستعمل بحالة جيدة',description:'فلتر صفائحي مناسب لخطوط تصفية زيت الزيتون، جاهز للاستعمال، مع إمكانية المعاينة قبل الشراء.',media:[{type:'image',url:'assets/filter-demo.svg'}],createdAt:'2026-09-27T10:00:00Z'},
{id:'demo3',kind:'بيع',category:'المعدات والتجهيزات',title:'خزان ستانلس ستيل 1000 لتر',price:'12,000 درهم',location:'العطاوية',quantity:'2',unit:'معصرة',phone:'0634567890',whatsapp:'0634567890',condition:'مستعمل',description:'خزانات ستانلس ستيل مخصصة لحفظ زيت الزيتون، سعة 1000 لتر للخزان الواحد.',media:[{type:'image',url:'assets/tank-demo.svg'}],createdAt:'2026-09-26T10:00:00Z'},
{id:'demo4',kind:'شراء',category:'المعدات والتجهيزات',title:'مطلوب مضخة زيت غذائية',price:'الميزانية حسب الحالة',location:'بني ملال',quantity:'1',unit:'معصرة مهنية',phone:'0645678901',whatsapp:'0645678901',condition:'مستعمل أو جديد',description:'نبحث عن مضخة مناسبة لضخ زيت الزيتون، مع ذكر القدرة والحالة والسعر المقترح.',media:[{type:'image',url:'assets/pump-demo.svg'}],createdAt:'2026-09-25T10:00:00Z'}];
let objectUrls=new Map();
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function listings(){try{const x=JSON.parse(localStorage.getItem(KEY));return Array.isArray(x)&&x.length?x:demo}catch{return demo}}
function saveListings(a){localStorage.setItem(KEY,JSON.stringify(a))}
function wa(n){let x=String(n||'').replace(/\D/g,'');if(x.startsWith('0'))x='212'+x.slice(1);if(!x.startsWith('212'))x='212'+x;return 'https://wa.me/'+x}
function phoneHref(n){return 'tel:'+String(n||'').replace(/\s/g,'')}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(MEDIA_STORE))r.result.createObjectStore(MEDIA_STORE,{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function putMedia(file){const db=await openDB();const id='media_'+Date.now()+'_'+Math.random().toString(36).slice(2,9);await new Promise((resolve,reject)=>{const tx=db.transaction(MEDIA_STORE,'readwrite');tx.objectStore(MEDIA_STORE).put({id,blob:file,type:file.type,name:file.name,size:file.size});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});return {id,type:file.type.startsWith('video/')?'video':'image',name:file.name,size:file.size}}
async function getMedia(id){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(MEDIA_STORE,'readonly');const r=tx.objectStore(MEDIA_STORE).get(id);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error)})}
async function deleteMedia(id){try{const db=await openDB();await new Promise((resolve,reject)=>{const tx=db.transaction(MEDIA_STORE,'readwrite');tx.objectStore(MEDIA_STORE).delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}catch{}}
async function mediaUrl(m){if(!m)return null;if(m.url)return m.url;if(!m.id)return null;if(objectUrls.has(m.id))return objectUrls.get(m.id);const item=await getMedia(m.id);if(!item)return null;const u=URL.createObjectURL(item.blob);objectUrls.set(m.id,u);return u}
async function firstMedia(x){const m=(x.media&&x.media[0])||{url:x.image||'assets/oil-demo.svg',type:'image'};return {meta:m,url:await mediaUrl(m)} }
async function cardHtml(x){const fm=await firstMedia(x);const isVideo=fm.meta.type==='video';return `<article class="card"><a href="listing.html?id=${encodeURIComponent(x.id)}"><div class="card-image">${isVideo?`<video src="${esc(fm.url)}" muted playsinline preload="metadata"></video>`:`<img src="${esc(fm.url||'assets/oil-demo.svg')}" alt="${esc(x.title)}" loading="lazy">`}<span class="badge ${x.kind==='بيع'?'sale':'buy'}">${x.kind==='بيع'?'للبيع':'مطلوب للشراء'}</span>${(x.media||[]).length>1?`<span class="media-count">▧ ${(x.media||[]).length}</span>`:''}</div><div class="card-body"><h3>${esc(x.title)}</h3><div class="price">${esc(x.price||'السعر عند التواصل')}</div><div class="meta"><span>📍 ${esc(x.location)}</span><span>${x.category==='زيت الزيتون'?'🫒':'⚙️'} ${esc(x.category)}</span></div><div class="card-footer"><small>${esc(x.quantity||'')} ${x.quantity?'— ':''}${esc(x.condition||'')}</small><span class="link">التفاصيل ←</span></div></div></a></article>`}
async function getById(id){return listings().find(x=>x.id===id)}
async function renderGrid(el,arr){if(!arr.length){el.innerHTML=`<div class="empty" style="grid-column:1/-1"><b>لا توجد نتائج حالياً</b>غيّر خيارات البحث أو انشر أول إعلان في المنصة.</div>`;return}el.innerHTML=await Promise.all(arr.map(cardHtml)).then(x=>x.join(''))}
function filterData(){const c=document.getElementById('cat')?.value||'الكل',k=document.getElementById('kind')?.value||'الكل',q=(document.getElementById('q')?.value||'').trim().toLowerCase();return listings().filter(x=>(c==='الكل'||x.category===c)&&(k==='الكل'||x.kind===k)&&(!q||JSON.stringify(x).toLowerCase().includes(q))).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt))}
async function initHome(){const grid=document.getElementById('homeGrid');if(grid)await renderGrid(grid,listings().slice().sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,4));document.getElementById('searchGo')?.addEventListener('click',()=>{const q=document.getElementById('homeSearch').value.trim(),c=document.getElementById('homeCat').value;location.href='search.html?q='+encodeURIComponent(q)+'&cat='+encodeURIComponent(c)});document.getElementById('homeSearch')?.addEventListener('keydown',e=>{if(e.key==='Enter')document.getElementById('searchGo').click()})}
async function initSearch(){const p=new URLSearchParams(location.search);const q=p.get('q')||'';const cat=p.get('cat')||'الكل';document.getElementById('q').value=q;document.getElementById('cat').value=cat;const run=async()=>await renderGrid(document.getElementById('grid'),filterData());['cat','kind','q'].forEach(id=>document.getElementById(id)?.addEventListener('input',run));await run()}
async function initDetail(){const x=await getById(new URLSearchParams(location.search).get('id'));const root=document.getElementById('detail');if(!x){root.innerHTML='<div class="empty">الإعلان غير موجود.</div>';return}const media=x.media||[{type:'image',url:x.image||'assets/oil-demo.svg'}];const resolved=await Promise.all(media.map(async m=>({m,url:await mediaUrl(m)})));root.innerHTML=`<div class="detail-layout"><div class="gallery"><div class="gallery-main" id="galleryMain"></div><div class="gallery-thumbs" id="galleryThumbs">${resolved.map((r,i)=>`<button class="thumb ${i===0?'active':''}" data-i="${i}">${r.m.type==='video'?`<span>▶</span>`:`<img src="${esc(r.url)}" alt="">`}</button>`).join('')}</div></div><div class="detail-box"><span class="eyebrow">${x.kind==='بيع'?'عرض للبيع':'طلب شراء'} · ${esc(x.category)}</span><h1>${esc(x.title)}</h1><div class="detail-price">${esc(x.price||'السعر عند التواصل')}</div><div class="meta"><span>📍 ${esc(x.location)}</span><span>🕒 منشور حديثاً</span></div><div class="specs"><div class="spec"><small>الكمية</small><b>${esc(x.quantity||'—')}</b></div><div class="spec"><small>الحالة</small><b>${esc(x.condition||'—')}</b></div><div class="spec"><small>الوحدة / الجهة</small><b>${esc(x.unit||'—')}</b></div>${x.category==='زيت الزيتون'?`<div class="spec"><small>الترخيص الصحي</small><b>${esc(x.onssa||'—')}</b></div>`:''}</div><h3>الوصف</h3><p class="detail-desc">${esc(x.description||'لا يوجد وصف إضافي.')}</p><div class="contact"><a class="btn primary" href="${phoneHref(x.phone)}">📞 الاتصال</a><a class="btn whatsapp" target="_blank" rel="noopener" href="${wa(x.whatsapp||x.phone)}">◉ واتساب</a></div><div class="notice" style="margin-top:14px">التواصل يتم مباشرة مع صاحب الإعلان. المنصة لا تتدخل في إتمام المعاملة بين الطرفين.</div></div></div>`;const main=document.getElementById('galleryMain');const show=async i=>{const r=resolved[i];main.innerHTML=r.m.type==='video'?`<video class="gallery-media" src="${esc(r.url)}" controls playsinline preload="metadata"></video>`:`<img class="gallery-media" src="${esc(r.url)}" alt="${esc(x.title)}">`;document.querySelectorAll('.thumb').forEach((b,j)=>b.classList.toggle('active',j===i))};document.querySelectorAll('.thumb').forEach(b=>b.addEventListener('click',()=>show(Number(b.dataset.i))));await show(0)}
async function initPublish(){const form=document.getElementById('publishForm');const input=document.getElementById('mediaInput'),preview=document.getElementById('mediaPreview');let selected=[];document.getElementById('lawLink')?.addEventListener('click',e=>{e.preventDefault();document.getElementById('lawModal').classList.add('open')});document.querySelectorAll('[data-close-law]').forEach(x=>x.addEventListener('click',()=>document.getElementById('lawModal').classList.remove('open')));input?.addEventListener('change',()=>{selected=[...input.files];renderSelected()});function renderSelected(){preview.innerHTML='';selected.forEach((file,i)=>{const box=document.createElement('div');box.className='upload-item';const u=URL.createObjectURL(file);box.innerHTML=file.type.startsWith('video/')?`<video src="${u}" muted playsinline controls></video>`:`<img src="${u}" alt="">`;const info=document.createElement('div');info.className='upload-item-info';info.textContent=file.name;const del=document.createElement('button');del.type='button';del.className='remove-media';del.textContent='×';del.addEventListener('click',()=>{URL.revokeObjectURL(u);selected.splice(i,1);renderSelected()});box.append(info,del);preview.appendChild(box)})}form?.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(form);const x=Object.fromEntries(fd.entries());if(!fd.get('agree'))return alert('يرجى الموافقة على القانون الداخلي أولاً.');if(x.category==='زيت الزيتون'&&x.onssa!=='حاصل')return alert('إعلانات زيت الزيتون مخصصة للوحدات الحاصلة على الترخيص الصحي.');if(selected.length>8)return alert('يمكن إرفاق 8 ملفات كحد أقصى.');for(const f of selected){const max=f.type.startsWith('video/')?50*1024*1024:8*1024*1024;if(f.size>max)return alert(`الملف ${f.name} يتجاوز الحجم المسموح.`)}const media=[];for(const f of selected)media.push(await putMedia(f));x.id='ad_'+Date.now();x.createdAt=new Date().toISOString();x.media=media;delete x.agree;delete x.mediaInput;const old=listings().filter(z=>!String(z.id).startsWith('demo'));saveListings([x,...old]);location.href='search.html?published='+encodeURIComponent(x.id)})}
window.addEventListener('beforeunload',()=>objectUrls.forEach(u=>URL.revokeObjectURL(u)));
window.Souk={listings,saveListings,initHome,initSearch,initDetail,initPublish};
